// Portado 1:1 de SAVINGS_TIPS en public/js/app.js.
export const SAVINGS_TIPS: string[] = [
  '💡 Ahorra primero y gasta después — destina el 20% de tu ingreso a ahorros antes de cualquier gasto.',
  '💡 Espera 24 horas antes de cualquier compra impulsiva. Si al día siguiente aún lo quieres, evalúalo.',
  '💡 Registra cada gasto, incluso los más pequeños. Los cafés y snacks diarios suman cientos al mes.',
  '💡 Usa la regla 50/30/20: 50% necesidades, 30% deseos, 20% ahorros. Simple y efectiva.',
  '💡 Automatiza tus ahorros transfiriendo dinero apenas recibes tu sueldo, no al final del mes.',
  '💡 Paga siempre el total de tu tarjeta de crédito para evitar intereses que crecen rápidamente.',
  '💡 Ponle nombre y monto a cada meta de ahorro — es más fácil mantenerse motivado con un objetivo claro.',
  '💡 Un pequeño ahorro constante todos los meses supera a un gran ahorro ocasional.',
  '💡 Antes de gastar, pregúntate: ¿esto me acerca o me aleja de mi meta financiera?',
  '💡 Cada vez que evitas un gasto impulsivo, transfiere ese dinero a tu ahorro para verlo crecer.',
  '💡 Revisa tus gastos por categoría cada semana — no esperes al cierre del mes para descubrir sorpresas.',
  '💡 El interés compuesto es tu mejor aliado: mientras antes empieces a ahorrar, más crecerá tu dinero.',
  '💡 Compara precios antes de comprar — unos minutos de búsqueda pueden ahorrarte bastante.',
  '💡 Negocia tus servicios: internet, seguros y membresías suelen dar descuentos si simplemente pides.',
  '💡 Cocinar en casa puede costar 3 veces menos que comer fuera — y es más saludable.',
  '💡 Evita pagar solo el mínimo de tarjeta de crédito — así solo pagas intereses y la deuda no termina.',
  '💡 Cancela una suscripción antes de contratar otra — las que olvidamos son dinero perdido cada mes.',
  '💡 Planifica tu lista del supermercado antes de ir — reduces el gasto innecesario hasta en un 30%.',
  '💡 Un fondo de emergencia de 3 a 6 meses de gastos es tu red de seguridad financiera más importante.',
  '💡 Diferencia entre "querer" y "necesitar" antes de cada compra importante — la respuesta cambia todo.',
  '💡 Lleva un diario financiero semanal: 10 minutos revisando tus gastos transforma tus hábitos en 30 días.',
  '💡 Usar efectivo para gastos discrecionales hace más visible cuánto gastas — pruébalo un mes.',
  '💡 Paga tus deudas de mayor a menor tasa de interés — así ahorras más en intereses totales.',
  '💡 Si recibes un ingreso extra como bono, destina al menos el 50% a ahorros o pago de deudas.',
  '💡 Compra artículos de temporada cuando la temporada termina — los descuentos pueden ser del 50-70%.',
  '💡 Aprende a decir no a gastos sociales que no puedes pagar — tus finanzas deben ser tu prioridad.',
  '💡 Revisa tu plan de celular mensualmente — muchas veces pagas por servicios que ya no usas.',
  '💡 Usa aplicaciones de cashback y cupones para compras que harías de todas formas.',
  '💡 Un presupuesto no es una restricción, es un plan que te da libertad para gastar sin culpa.',
  '💡 Invertir en tu salud es el ahorro más inteligente — prevenir enfermedades es mucho más barato.',
  '💡 Antes de endeudarte, calcula cuántos días de trabajo necesitas para pagar esa deuda.',
  '💡 Los gastos pequeños se acumulan: S/ 10 al día en café son más de S/ 3,600 al año.',
  '💡 Diversifica tus fuentes de ingreso — depender de uno solo es el mayor riesgo financiero personal.',
  '💡 El mejor momento para empezar a ahorrar fue ayer; el segundo mejor momento es exactamente hoy.',
  '💡 La educación financiera es la inversión con el mayor retorno posible — lee, aprende, aplica.',
  '💡 Compra activos, no pasivos: cosas que generen valor a futuro, no que lo pierdan con el tiempo.',
  '💡 Usa tu tarjeta de crédito solo para compras que ya tienes el dinero en efectivo para pagar.',
  '💡 Revisa tus seguros anualmente — podrías estar pagando de más o por coberturas que no necesitas.',
  '💡 El precio por unidad importa más que el precio total — compara costos por kilo, litro o uso.',
  '💡 Ten claro tu número: ¿cuánto necesitas ahorrar para ser financieramente libre? Escríbelo.',
  '💡 Los gastos hormiga (pequeños y frecuentes) pueden llevarse hasta el 20% de tu ingreso sin que lo notes.',
  '💡 Invertir en habilidades que aumenten tus ingresos es el activo más seguro que existe.',
  '💡 Separa tus cuentas: una para gastos fijos, otra para ahorro y otra para gastos variables.',
  '💡 Planifica tus viajes con anticipación — los precios de vuelos y hoteles suben cerca de la fecha.',
  '💡 No compres por emoción negativa. Si estás triste o estresado, espera antes de abrir la billetera.',
  '💡 El lujo de hoy puede ser la deuda de mañana — vive bien dentro de tus posibilidades reales.',
  '💡 Revisa los estados de cuenta mensualmente para detectar cobros no autorizados o errores.',
  '💡 Ahorra el aumento salarial — si vivías sin ese dinero extra, no lo extrañarás si lo guardas.',
  '💡 La gratificación diferida — saber esperar por lo que quieres — es la habilidad financiera más poderosa.',
  '💡 Un carro económico en mantenimiento es mejor que uno lujoso que vacía tu cuenta cada mes.',
  '💡 Compra de segunda mano lo que no necesita ser nuevo: electrónicos, muebles y ropa en buen estado.',
  '💡 Los libros de finanzas personales y los videos educativos gratuitos son tu mejor inversión de tiempo.',
  '💡 No confundas precio con valor — lo barato que compras dos veces termina saliendo más caro.',
  '💡 Antes de reemplazar, repara. Muchos productos duran mucho más con un pequeño mantenimiento.',
  '💡 Calcula el costo en horas de trabajo de tus compras. ¿Vale la pena trabajar X horas por esto?',
  '💡 Ten un presupuesto para diversión — ser frugal no significa privarte de todo, sino elegir bien.',
  '💡 Reduce gastos de energía en casa: apaga luces, desenchufa aparatos — el ahorro es constante.',
  '💡 El seguro de salud es un ahorro, no un gasto — una emergencia médica puede arruinar tus finanzas.',
  '💡 Compra en cantidad lo que consumes mucho y tiene larga vida útil cuando hay descuentos.',
  '💡 Antes de ir al supermercado, come algo — las compras con hambre siempre salen más caras.',
  '💡 Haz un inventario antes de comprar algo nuevo — evita tener duplicados de cosas que ya tienes.',
  '💡 El tiempo libre es valioso — evalúa si un servicio que pagas realmente te ahorra suficiente tiempo.',
  '💡 Compara bancos y entidades financieras — las tasas de interés en ahorros varían mucho entre ellos.',
  '💡 La mejor inversión es eliminar deudas con altos intereses — libera flujo de caja inmediatamente.',
  '💡 No financies lo que se consume: comida, ropa y entretenimiento no deben comprarse a crédito.',
  '💡 Habla de dinero en familia — los objetivos financieros compartidos se alcanzan más fácilmente.',
  '💡 Configura alertas de gasto en tu banco — saber en tiempo real cuánto gastas cambia tus hábitos.',
  '💡 El marketing está diseñado para hacerte gastar — sé consciente de las estrategias que te rodean.',
  '💡 Cuando algo pasa de moda rápidamente, probablemente no valía la pena comprarlo desde el inicio.',
  '💡 Calcula tu patrimonio neto cada mes — activos menos deudas. Si crece, vas exactamente por buen camino.',
  '💡 Tener una meta específica hace que ahorrar sea más fácil, más motivador y más constante.',
  '💡 Los hábitos financieros se forman en 66 días — dale tiempo a tus nuevos comportamientos.',
  '💡 Una persona frugal no es tacaña, es inteligente con su dinero — y eso se nota en su libertad.',
  '💡 Pagarle a tu yo futuro es tan importante como pagar tus deudas actuales — no lo postergues.',
  '💡 Aprende a distinguir entre un buen precio y una buena compra — no siempre son lo mismo.',
  '💡 Los errores financieros son lecciones valiosas — lo importante es no repetirlos dos veces.',
  '💡 El estrés financiero afecta tu salud — controlar tu dinero mejora tu bienestar integral.',
  '💡 Revisa si tienes dinero olvidado en cuentas antiguas o seguros sin reclamar — podría sorprenderte.',
  '💡 El 1% de mejora financiera cada semana equivale a una transformación completa en un año.',
  '💡 Celebra tus logros financieros — cuando alcances una meta, reconócelo antes de fijar la siguiente.',
  '💡 Una buena negociación puede ahorrarte tanto como meses de trabajo extra — practica ese músculo.',
  '💡 Evita garantías extendidas en casi todos los casos — el costo adicional rara vez vale la pena.',
  '💡 La disciplina financiera en los pequeños detalles es lo que se refleja en los grandes resultados.',
  '💡 Si no sabes adónde va tu dinero, empieza a registrar cada sol gastado — la respuesta te sorprenderá.',
  '💡 Diferencia entre precio y costo total: incluye mantenimiento, seguro y vida útil del producto.',
  '💡 Invertir no es solo para ricos — con montos pequeños pero constantes ya estás construyendo riqueza.',
  '💡 La paciencia es el ingrediente secreto de toda buena estrategia financiera — no hay atajos reales.',
  '💡 No compares tu situación financiera con la de otros — cada persona tiene su propio camino.',
  '💡 Aprende sobre tasas de interés — entender cómo funcionan puede ahorrarte miles de soles.',
  '💡 Tener múltiples metas de ahorro activas a la vez multiplica tu motivación para guardar dinero.',
  '💡 Los gastos de estatus social — marcas, artículos de lujo — son una de las principales trampas.',
  '💡 El ahorro es un músculo — mientras más lo ejercitas, más natural y automático se vuelve.',
  '💡 Si no puedes pagarlo dos veces, probablemente no puedes permitirtelo ni una vez — reflexiona.',
  '💡 Tu peor enemigo financiero puede ser tu yo impulsivo — planifica con calma y decide con la cabeza.',
  '💡 Un presupuesto realista incluye gastos de ocio y socialización — ser muy estricto lleva al abandono.',
  '💡 Cada sol bien administrado hoy es un sol libre mañana para hacer lo que realmente importa.',
  '💡 Comparte tus metas financieras con alguien de confianza — la responsabilidad compartida multiplica el éxito.',
  '💡 Antes de gastar en entretenimiento, busca opciones gratuitas — museos, parques y eventos sin costo.',
  '💡 El dinero ahorrado en gastos innecesarios equivale a dinero ganado sin trabajar más horas.',
  '💡 La independencia financiera no es un destino sino un camino — cada pequeña decisión de hoy cuenta.',
  '💡 Revisa este panel cada día — quien mide sus finanzas las mejora; quien las ignora, las pierde.',
];

// 1 consejo diferente por día, igual que renderTip() en app.js.
export function todaysTipIndex(): number {
  const d = new Date();
  const start = new Date(d.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((d.getTime() - start.getTime()) / 86400000);
  return dayOfYear % SAVINGS_TIPS.length;
}
